name: Sam Selikoff
# pygments: true
highlighter: pygments
# permalink: /blog/:year/:month/:day/:title
permalink: /blog/:title
# paginate: 5
# paginate_path: "blog/page:num"
exclude: ['node_modules', 'gulpfile.js']

# markdown: maruku
markdown: redcarpet
excerpt_separator: "<!-- more -->"

gems:
  - pry
  - pry-debugger
  - jekyll-compass
  - jekyll-redirect-from
  - active_support

collections:
  talks:
    output: true
  writing:
    output: true
    permalink: /:collection/:path/


# redcarpet:
#     extensions: [with_toc_data]

sass:
  sass_dir: _sass
  style:  expanded  # nested|expanded|compact|compressed
  deploy_style: compressed  # nested|expanded|compact|compressed
  # "deploy_style:" is used only for building the site
  # (ie: not using the --watch flag)

  compile_in_place: false   # true|false
  # If true, compiles sass directly into your jekyll source directory
  # As well as your destination directory
